config/routes.rb
BoomBamSplash::Application.routes.draw do
  resources :sounds
  root :to => "sounds#index"
end

app/models/sound.rb
class Sound
  include HasherCrasher::Ohm

  before_save :underscore_name


  private

  def underscore_name
    self.name = name.underscore
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  def index
    @sounds = Sound.all
  end

  def new
    @sound = Sound.new
  end

  def create
    @sound = Sound.new params[:sound]
    if @sound.save
      redirect_to sounds_path
    else
      render :action => "new"
    end
  end

  def show
    @sound = Sound.find params[:id]
    send_data @sound.data, :filename => "sound.mp3", :type => "audio/mpeg"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoomBamSplash</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! html

%html
  %head
    %title
      = yield(:title) || "Boom Bam Splash"
    = stylesheet_link_tag 'screen.css'
  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
          
        - if show_title?
          %h1=h yield(:title)

      = yield

app/views/sounds/index.html.haml
#sounds
  - @sounds.each do |sound|
    .sound
      %p= sound.name
      %audio{:src => sound_path(sound), :controls => "true"}
  %div{:style => "clear:both;"}

= link_to "Add a new sound", new_sound_path

app/views/sounds/new.html.haml
= form_for @sound, :html => {:multipart => true} do |f|
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label :data_file
    = f.file_field :data_file
  %p
    = f.submit